=== What's New in 2.6 Since 2.5

This section covers the changes made from version 2.5 to version 2.6.
For changes in earlier version, see <<history>>.

[[x26-kafka-client]]
==== Kafka Client Version

This version requires the 2.6.0 `kafka-clients`.

==== Listener Container Changes

The default `EOSMode` is now `BETA`.
See <<exactly-once>> for more information.

Various error handlers (that extend `FailedRecordProcessor`) and the `DefaultAfterRollbackProcessor` now reset the `BackOff` if recovery fails.
In addition, you can now select the `BackOff` to use based on the failed record and/or exception.
See <<seek-to-current>>, <<recovering-batch-eh>>, <<dead-letters>> and <<after-rollback>> for more information.

==== @KafkaLisener Changes

When using manual partition assignment, you can now specify a wildcard for determining which partitions should be reset to the initial offset.
In addition, if the listener implements `ConsumerSeekAware`, `onPartitionsAssigned()` is called after the manual assignment.
(Also added in version 2.5.5).
See <<manual-assignment>> for more information.
